<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <AssemblyName>SessionModManagerCore</AssemblyName>
    <RootNamespace>SessionModManagerCore</RootNamespace>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <DocumentationFile>
    </DocumentationFile>
    <Version>1.11.5</Version>
    <AssemblyVersion>1.11.5.0</AssemblyVersion>
    <FileVersion>1.11.5.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ViewModels\DownloadableMap.cs" />
    <Compile Remove="ViewModels\UploadAssetViewModel.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="modmanager.csv" />
    <None Remove="modmanager.json" />
    <None Remove="UAssetAPI.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ini-parser-netstandard" Version="2.5.3" />
    <PackageReference Include="MegaApiClient" Version="1.10.5" />
    <PackageReference Include="NLog" Version="6.1.3" />
    <PackageReference Include="SharpCompress" Version="0.49.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Page Include="UAssetAPI.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="UAssetAPI">
      <HintPath>..\..\UAssetAPI\UAssetAPI\bin\Debug\net8.0\UAssetAPI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>