<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>SessionModManager</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Label="Avalonia">
    <AvaloniaNameGeneratorDefaultFieldModifier>Public</AvaloniaNameGeneratorDefaultFieldModifier>
    <ApplicationIcon>Resources\new_switcher.ico</ApplicationIcon>
    <AssemblyVersion>3.0.5.0</AssemblyVersion>
    <FileVersion>3.0.5.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="Resources\defaultMap1.png" />
    <None Remove="Resources\defaultMap2.png" />
    <None Remove="Resources\defaultMap3.png" />
    <None Remove="Resources\new_switcher.ico" />
    <None Remove="Resources\ParkPieces\SM_Pyramid_01.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\defaultMap1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\defaultMap2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\defaultMap3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\new_switcher.ico" />
    <Content Include="Resources\ParkPieces\SM_Pyramid_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.0" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.0" />
    <PackageReference Include="Markdown.Avalonia" Version="11.0.2" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.2.0" />
    <PackageReference Include="PanAndZoom" Version="11.3.0.1" />
    <PackageReference Include="Projektanker.Icons.Avalonia" Version="9.6.2" />
    <PackageReference Include="Projektanker.Icons.Avalonia.MaterialDesign" Version="9.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SessionModManagerCore\SessionModManagerCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\new_switcher.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Bank_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Bank_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Bank_03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Bench_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Concrete_Spine_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Funbox_Floor_01_3m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Funbox_Wall_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Funbox_Wall_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Halfpipe_01_Middle.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Halfpipe_01_Ramp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Pyramid_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_2m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_3m_Angled.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_4m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_Corner_45_1m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_Corner_90_1m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_Corner_90_2m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_End.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_Funbox_Wall_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_Pyramid_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_01_Stairs_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_02_2m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_02_4m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_02_Corner_45_1m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_02_Corner_90_1m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Rail_02_Corner_90_2m.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Roll_Ramp_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Spine_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Stairs_Small_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Stairs_Small_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Table_Benches_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\ParkPieces\SM_Wave_Ramp_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Windows\RenameMapWindow.axaml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Windows\UpdateWindow.axaml" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="SET SMMPATH=$(ProjectDir)..\SMMUpdater\bin\Debug\net8.0&#xD;&#xA;SET TARGETPATH=$(OutDir)&#xD;&#xA;&#xD;&#xA;if $(ConfigurationName) == Release SET SMMPATH=$(ProjectDir)..\SMMUpdater\bin\Release\net8.0\publish\windows&#xD;&#xA;if $(ConfigurationName) == Release SET TARGETPATH=$(TargetDir)publish\windows\&#xD;&#xA;&#xD;&#xA;echo %25SMMPATH%25&#xD;&#xA;echo &quot;%25TARGETPATH%25releases&quot;&#xD;&#xA;&#xD;&#xA;mkdir &quot;%25TARGETPATH%25releases&quot;&#xD;&#xA;xcopy /y &quot;%25SMMPATH%25\SMMUpdater.exe&quot;  &quot;%25TARGETPATH%25releases&quot;&#xD;&#xA;xcopy /y &quot;%25SMMPATH%25\SMMUpdater.dll&quot;  &quot;%25TARGETPATH%25releases&quot;&#xD;&#xA;xcopy /y &quot;%25SMMPATH%25\SMMUpdater.deps.json&quot;  &quot;%25TARGETPATH%25releases&quot;&#xD;&#xA;xcopy /y &quot;%25SMMPATH%25\SMMUpdater.runtimeconfig.json&quot;  &quot;%25TARGETPATH%25releases&quot;&#xD;&#xA;&#xD;&#xA;cd &quot;%25TARGETPATH%25&quot;&#xD;&#xA;del *.pdb /q" />
  </Target>
</Project>
